name: CMake Build (macOS x86-64)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      working-directory: ${{runner.workspace}}
      run: brew install sdl2 qt@5 libslirp libarchive libepoxy
    - name: Create build environment
      run: mkdir ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH="$(brew --prefix qt@5);$(brew --prefix libarchive)" -DMACOS_BUNDLE_LIBS=ON -DMACOS_BUILD_DMG=ON
    - name: Make
      working-directory: ${{runner.workspace}}/build
      run: |
        make -j$(sysctl -n hw.ncpu)
    - uses: actions/upload-artifact@v1
      with:
        name: melonDS.dmg
        path: ${{runner.workspace}}/build/melonDS.dmg
