name: CMake Build (FreeBSD x86-64)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      uses: vmactions/freebsd-vm@main
      with:
        prepare: |
          pkg install -y git wget pkgconf glib meson ninja cmake qt5-core qt5-gui qt5-widgets sdl2
          wget https://gitlab.freedesktop.org/slirp/libslirp/-/archive/v4.4.0/libslirp-v4.4.0.zip
          unzip libslirp-v4.4.0.zip
          cd libslirp-v4.4.0
          meson build
          ninja -C build install
          mkdir ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          make
    - uses: actions/upload-artifact@v1
      with:
        name: melonDS
        path: ${{runner.workspace}}/build/dist
